Add new operators and extractors deep dive blog post.
OpenLineage/website pull request #60
Opened 2022-08-01 20:24 UTC by denimalpaca

Signed-off-by: Benji Lampel <benjamin@astronomer.io>

2022-08-01 21:19 UTC, rossturk requested changes
Awesome post! Need some artwork + bit of formatting, then we are gtg.

2022-08-01 21:19 UTC, rossturk commented on contents/blog/operators-and-extractors-technical-deep-dive/index.mdx
> +image: ./image.svg
I sent you some artwork that you can use for this, and for banner.svg.

2022-08-01 21:19 UTC, rossturk commented on contents/blog/operators-and-extractors-technical-deep-dive/index.mdx
> +Note: This blog post describes the relationships of the operators and extractors only for `Airflow>=2.3` and `OpenLineage>=0.12.0`.
This Markdown renderer is collapsing this into a single paragraph without a blank line in between - this happens throughout.

2022-08-01 21:21 UTC, merobi-hub approved these changes
LGTM!

2022-08-02 16:45 UTC, rossturk approved these changes

2022-08-26 15:28 UTC, denimalpaca commented
@rossturk @merobi-hub any reason this hasn't been merged yet?

2022-09-07 02:33 UTC, merged